master: # 触发分支
  push: # 触发事件，包含多个Pipeline, 数组形式
    - name: pipeline-1 # Pipeline结构体
      stages:
        - name: stage-1 # Stage结构体
          jobs:
            - name: job-1 # Job结构体
              script: exit 12123123123
    - name: pipeline-2 # Pipeline结构体
      stages:
        - name: stage-2 # Stage结构体
          jobs:
            - name: job-1 # Job结构体
              script: echo hello
    - name: pipeline-3 # Pipeline结构体
      stages:
        - name: stage-2 # Stage结构体
          jobs:
            - name: job-1 # Job结构体
              script: echo hello